#!/usr/bin/env bash
# Rotate the NNF onion address (see TOR.md §3.5). NNF has no URL setting -- it
# bakes the absolute .onion URL into every ".rss" file, "index.xml", "sitemap.xml"
# and stored permalink -- so changing the address means a new Tor key AND a
# rewrite of everything already in the data directory.
#
# Run on the HOST, as root, from the directory holding "docker-compose.tor.yml":
#
#   sudo ./rotate-onion.sh                 # generate a fresh random address
#   sudo ./rotate-onion.sh ./vanity-dir    # install a key made offline with mkp224o
#   sudo ./rotate-onion.sh -y [dir]        # skip the confirmation prompt
#
# Override any of these with the environment:
#   TOR_HS_DIR   (default /var/lib/tor/nnf)
#   TOR_SERVICE  (default tor@default)
#   TOR_USER     (default debian-tor)
#   DATA_DIR     (default <script dir>/data)
#   COMPOSE_FILE (default <script dir>/docker-compose.tor.yml)
set -euo pipefail

TOR_HS_DIR=${TOR_HS_DIR:-/var/lib/tor/nnf}
TOR_SERVICE=${TOR_SERVICE:-tor@default}
TOR_USER=${TOR_USER:-debian-tor}

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
DATA_DIR=${DATA_DIR:-$SCRIPT_DIR/data}
COMPOSE_FILE=${COMPOSE_FILE:-$SCRIPT_DIR/docker-compose.tor.yml}

ASSUME_YES=0
[ "${1:-}" = "-y" ] && { ASSUME_YES=1; shift; }
VANITY_DIR=${1:-}

die () { echo "error: $*" >&2; exit 1; }

[ "$(id -u)" = 0 ]        || die "run as root (needs $TOR_HS_DIR and systemctl)"
command -v docker >/dev/null || die "docker not found"
[ -f "$COMPOSE_FILE" ]    || die "no compose file at $COMPOSE_FILE"
[ -d "$DATA_DIR" ]        || die "no data directory at $DATA_DIR"
[ -f "$TOR_HS_DIR/hostname" ] || die "no current onion at $TOR_HS_DIR/hostname"

if [ -n "$VANITY_DIR" ]; then
	for f in hs_ed25519_secret_key hs_ed25519_public_key hostname; do
		[ -f "$VANITY_DIR/$f" ] || die "vanity dir missing $f"
	done
fi

OLD=$(tr -d '[:space:]' < "$TOR_HS_DIR/hostname")
echo "current address : $OLD"
if [ -n "$VANITY_DIR" ]; then
	NEW=$(tr -d '[:space:]' < "$VANITY_DIR/hostname")
	echo "new address     : $NEW  (from $VANITY_DIR)"
else
	echo "new address     : freshly generated by Tor"
fi
echo "data directory  : $DATA_DIR"
echo
echo "This stops the forum, replaces the Tor key, and rewrites every occurrence"
echo "of the old address in $DATA_DIR. The old key is kept as a .bak (shred it"
echo "yourself once you're sure)."
if [ "$ASSUME_YES" != 1 ]; then
	printf 'Continue? [y/N] '
	read -r ans
	case "$ans" in y|Y|yes) ;; *) echo aborted; exit 1;; esac
fi

echo "==> stopping forum container"
docker compose -f "$COMPOSE_FILE" stop forum

echo "==> stopping $TOR_SERVICE"
systemctl stop "$TOR_SERVICE"

STAMP=$(date +%Y%m%d-%H%M%S)
echo "==> backing up old key to ${TOR_HS_DIR}.${STAMP}.bak"
mv "$TOR_HS_DIR" "${TOR_HS_DIR}.${STAMP}.bak"
install -d -m700 -o "$TOR_USER" -g "$TOR_USER" "$TOR_HS_DIR"

if [ -n "$VANITY_DIR" ]; then
	echo "==> installing vanity key"
	cp "$VANITY_DIR/hs_ed25519_secret_key" "$VANITY_DIR/hs_ed25519_public_key" \
	   "$VANITY_DIR/hostname" "$TOR_HS_DIR/"
	chown -R "$TOR_USER:$TOR_USER" "$TOR_HS_DIR"
	chmod 600 "$TOR_HS_DIR"/hs_ed25519_* "$TOR_HS_DIR/hostname"
fi

echo "==> starting $TOR_SERVICE"
systemctl start "$TOR_SERVICE"

# wait for Tor to (re)create the hostname
i=0
while [ ! -s "$TOR_HS_DIR/hostname" ]; do
	i=$((i + 1)); [ "$i" -gt 30 ] && die "Tor did not produce $TOR_HS_DIR/hostname"
	sleep 1
done
NEW=$(tr -d '[:space:]' < "$TOR_HS_DIR/hostname")
[ "$NEW" != "$OLD" ] || die "address unchanged ($NEW) -- Tor reused the old key?"

echo "==> rewriting $OLD -> $NEW in $DATA_DIR"
# escape dots for the sed pattern; onion charset is [a-z2-7] so nothing else needs it
OLD_RE=$(printf '%s' "$OLD" | sed 's/\./\\./g')
MATCHES=$(grep -rlF "$OLD" "$DATA_DIR" || true)
if [ -n "$MATCHES" ]; then
	printf '%s\n' "$MATCHES" | while IFS= read -r f; do
		sed -i "s/$OLD_RE/$NEW/g" "$f"
	done
fi

echo "==> dropping generated indexes (regenerated on next post)"
find "$DATA_DIR" -name index.xml -delete
rm -f "$DATA_DIR/sitemap.xml"

LEFT=$(grep -rlF "$OLD" "$DATA_DIR" || true)
[ -z "$LEFT" ] || { echo "WARNING: old address still present in:"; echo "$LEFT"; }

echo "==> starting forum container"
docker compose -f "$COMPOSE_FILE" up -d

cat <<EOF

done.
  old : $OLD   (key backed up at ${TOR_HS_DIR}.${STAMP}.bak -- shred when sure)
  new : $NEW

still to do by hand:
  * update the Host filter in .htaccess.docker (TOR.md §5.2) and rebuild:
      docker compose -f $COMPOSE_FILE up -d --build
  * recreate client-auth files under $TOR_HS_DIR/authorized_clients/ (TOR.md §3.4)
  * post and delete one test thread to force index.xml / sitemap.xml to rebuild
  * announce $NEW to users through a channel they already trust
EOF
